# Generated by Django 3.2.6 on 2021-09-02 20:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('username', models.CharField(max_length=100)),
                ('client_information', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
