# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('username', models.CharField(max_length=100)),
                ('client_information', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
